# Generated by Django 3.0.5 on 2020-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couName', models.CharField(max_length=10)),
                ('couTea', models.CharField(max_length=5)),
                ('couId', models.IntegerField(default=0)),
                ('couTime', models.CharField(max_length=30)),
                ('couAllNum', models.IntegerField(default=0)),
                ('couLeftNum', models.IntegerField(default=0)),
                ('couPer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.CharField(max_length=5)),
                ('stuClass', models.CharField(max_length=10)),
                ('stuNum', models.IntegerField()),
                ('stuPasswd', models.CharField(max_length=256)),
            ],
        ),
    ]
