# Generated by Django 3.0.5 on 2020-06-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stuCou',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='couPer',
            field=models.TextField(default=''),
        ),
    ]
